### ISSUE TITLE
Connect to redis client on start, not new cache

### ISSUE THREAD

**Issue by zachferland** [3box/orbit-db-cache-redis#1]
Current orbit implementation actually creates and opens a separate db/store for every orbit store. For redis there is one store, should only open on start, and then load should just reference same db. Wonder why logically the cache is different db for each store, looks like not all keys are indexed by name, so will also have to prefix spaces as well.

**Comment by zachferland** [comment]
No pr to connect to - most code in this commit - https://github.com/3box/orbit-db-cache-redis/commit/8eaa34b8baf80169dd58871c180be217fd12177f

**Comment by oed** [comment]
Is the constructor always called with odbAddress, or is there a change needed in orbitdb? https://github.com/3box/orbit-db-cache-redis/commit/8eaa34b8baf80169dd58871c180be217fd12177f#diff-606970c7c6f881ca43fc6a7220b8fa74R14

**Comment by zachferland** [comment]
nope, but no change required since the actual constructor interface is basically the exported object at the bottom. So the load function, its the only the function which initializes the cache. (also almost same, orbit uses dir/address vs address)

**Comment by oed** [comment]
Aha, I see. Great!
